version: '{build}'
image: Visual Studio 2019

skip_branch_with_pr: true
pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - /release-.*/
  - /^\d+\.\d+\.\d+(-\S*)?$/
  
skip_commits:
  files:
    - '**/*.source.md'

build_script:
- cmd: ./build.cmd

test: off

artifacts:
- path: ./**/*.nupkg
  type: NuGetPackage
- path: ./**/*.snupkg
  type: NuGetPackage

deploy: off
